Repository saddlebackdev/hc-mobile-app-ui, pull requests merged in 2022-04, with the labels that each got.

#85 [dev] - AB#69096: [Giving][Android/Logged In/Out]- The "New Gift" and the "Thank you Confirmation" Pages are not opening completely! there is a Gap on the top of the pages
  src/modules/bottom-sheet/bottom-sheet.tsx
Labels: bug, enhancement

#88 [dev] - Bug AB#69096: [Giving][Android/Logged In/Out]- The "New Gift" and the "Thank you Confirmation" Pages are not opening completely! there is a Gap on the top of the pages
  src/modules/bottom-sheet/bottom-sheet.tsx
Labels: bug, ready for review

#83 [dev] - AB#65920 - Implement Header Search Bar
  src/modules/animatedHeader/animatedHeader.tsx
  src/modules/animatedHeader/animatedHeader.types.ts
Labels: ready for review
